package com.driveagent.android.manager

import com.driveagent.android.model.AppLanguage

class LanguageManager {
    
    private val translations = mapOf(
        // English
        "en" to mapOf(
            "Settings" to "Settings",
            "Language" to "Language",
            "Appearance" to "Appearance",
            "Show Top Bar" to "Show Top Bar",
            "Theme" to "Theme",
            "System" to "System",
            "Light" to "Light",
            "Dark" to "Dark",
            "Particle Effects" to "Particle Effects",
            "Effect Style" to "Effect Style",
            "Off" to "Off",
            "Orbit" to "Orbit",
            "Gradient" to "Gradient",
            "Units" to "Units",
            "Use Metric" to "Use Metric",
            "Metric Description" to "Speed in km/h, distance in meters/kilometers",
            "Imperial Description" to "Speed in mph, distance in feet/miles",
            "Trip" to "Trip",
            "Distance" to "Distance",
            "Max Speed" to "Max Speed",
            "Reset Trip" to "Reset Trip",
            "Speed Camera Alerts" to "Speed Camera Alerts",
            "Infinite Proximity" to "Infinite Proximity",
            "Infinite Proximity On" to "Always show the closest camera regardless of distance",
            "Infinite Proximity Off" to "Only show cameras within 2km",
            "Alert Distance" to "Alert Distance",
            "Alert Distance Description" to "Distance at which speed camera alerts are triggered",
            "Done" to "Done",
            "Speed Camera Ahead!" to "Speed Camera Ahead!",
            "Reduce speed immediately" to "Reduce speed immediately",
            "Limit" to "Limit",
            "Trip Distance" to "Trip Distance",
            "Searching for location..." to "Searching for location...",
            "Location Access Denied" to "Location Access Denied",
            "Location Permission Text" to "Please enable location access in Settings to use this app",
            "Open Settings" to "Open Settings",
            "Map" to "Map",
            "Speed Traps" to "Speed Traps",
            "Nearby Speed Cameras" to "Nearby Speed Cameras",
            "Close" to "Close",
            "No cameras nearby" to "No cameras nearby",
            "Welcome" to "Welcome to DriveAgent",
            "Onboarding Description" to "Your intelligent driving companion with real-time speed tracking and camera alerts",
            "Get Started" to "Get Started",
            "Skip" to "Skip"
        ),
        
        // Chinese Traditional
        "zh-TW" to mapOf(
            "Settings" to "設定",
            "Language" to "語言",
            "Appearance" to "外觀",
            "Show Top Bar" to "顯示頂部欄",
            "Theme" to "主題",
            "System" to "系統",
            "Light" to "淺色",
            "Dark" to "深色",
            "Particle Effects" to "粒子效果",
            "Effect Style" to "效果樣式",
            "Off" to "關閉",
            "Orbit" to "軌道",
            "Gradient" to "漸層",
            "Units" to "單位",
            "Use Metric" to "使用公制",
            "Metric Description" to "速度以公里/小時顯示，距離以公尺/公里顯示",
            "Imperial Description" to "速度以英里/小時顯示，距離以英尺/英里顯示",
            "Trip" to "行程",
            "Distance" to "距離",
            "Max Speed" to "最高速度",
            "Reset Trip" to "重設行程",
            "Speed Camera Alerts" to "測速照相提醒",
            "Infinite Proximity" to "無限距離",
            "Infinite Proximity On" to "始終顯示最近的測速相機，無論距離",
            "Infinite Proximity Off" to "僅顯示2公里內的測速相機",
            "Alert Distance" to "警報距離",
            "Alert Distance Description" to "觸發測速相機警報的距離",
            "Done" to "完成",
            "Speed Camera Ahead!" to "前方測速照相！",
            "Reduce speed immediately" to "請立即減速",
            "Limit" to "限速",
            "Trip Distance" to "行程距離",
            "Searching for location..." to "正在搜尋位置...",
            "Location Access Denied" to "位置存取被拒絕",
            "Location Permission Text" to "請在設定中啟用位置存取以使用此應用程式",
            "Open Settings" to "開啟設定",
            "Map" to "地圖",
            "Speed Traps" to "測速相機",
            "Nearby Speed Cameras" to "附近的測速相機",
            "Close" to "關閉",
            "No cameras nearby" to "附近沒有測速相機",
            "Welcome" to "歡迎使用 DriveAgent",
            "Onboarding Description" to "您的智能駕駛助手，提供即時速度追蹤和測速相機警報",
            "Get Started" to "開始使用",
            "Skip" to "跳過"
        ),
        
        // Spanish
        "es" to mapOf(
            "Settings" to "Configuración",
            "Language" to "Idioma",
            "Appearance" to "Apariencia",
            "Show Top Bar" to "Mostrar barra superior",
            "Theme" to "Tema",
            "System" to "Sistema",
            "Light" to "Claro",
            "Dark" to "Oscuro",
            "Particle Effects" to "Efectos de partículas",
            "Effect Style" to "Estilo de efecto",
            "Off" to "Desactivado",
            "Orbit" to "Órbita",
            "Gradient" to "Gradiente",
            "Units" to "Unidades",
            "Use Metric" to "Usar métrico",
            "Metric Description" to "Velocidad en km/h, distancia en metros/kilómetros",
            "Imperial Description" to "Velocidad en mph, distancia en pies/millas",
            "Trip" to "Viaje",
            "Distance" to "Distancia",
            "Max Speed" to "Velocidad máxima",
            "Reset Trip" to "Restablecer viaje",
            "Speed Camera Alerts" to "Alertas de cámaras de velocidad",
            "Infinite Proximity" to "Proximidad infinita",
            "Infinite Proximity On" to "Mostrar siempre la cámara más cercana sin importar la distancia",
            "Infinite Proximity Off" to "Solo mostrar cámaras dentro de 2km",
            "Alert Distance" to "Distancia de alerta",
            "Alert Distance Description" to "Distancia a la que se activan las alertas de cámaras",
            "Done" to "Hecho",
            "Speed Camera Ahead!" to "¡Cámara de velocidad adelante!",
            "Reduce speed immediately" to "Reduzca la velocidad inmediatamente",
            "Limit" to "Límite",
            "Trip Distance" to "Distancia del viaje",
            "Searching for location..." to "Buscando ubicación...",
            "Location Access Denied" to "Acceso a ubicación denegado",
            "Location Permission Text" to "Por favor habilite el acceso a la ubicación en Configuración",
            "Open Settings" to "Abrir configuración",
            "Map" to "Mapa",
            "Speed Traps" to "Cámaras de velocidad",
            "Nearby Speed Cameras" to "Cámaras de velocidad cercanas",
            "Close" to "Cerrar",
            "No cameras nearby" to "No hay cámaras cercanas",
            "Welcome" to "Bienvenido a DriveAgent",
            "Onboarding Description" to "Tu compañero inteligente de conducción con seguimiento de velocidad y alertas de cámaras",
            "Get Started" to "Comenzar",
            "Skip" to "Saltar"
        )
        // Add more languages as needed
    )
    
    fun localize(key: String, language: AppLanguage): String {
        return translations[language.code]?.get(key) ?: key
    }
}
